name: GitHub Merged Pull Request
description: Checks out the GitHub PR merge ref rather than the branch HEAD
author: https://github.com/seek-oss
requirements: []
configuration:
  properties:
    mode:
      type: string
    update_prs:
      type: boolean
    update_pipeline:
      type: string
    oldest_pr:
      type: integer
  required: []
